# Generated by Django 3.1.1 on 2021-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='profession',
            field=models.CharField(max_length=200),
        ),
    ]
